services:
  - type: web
    name: render-chess-sample
    env: static
    buildCommand: yarn install && yarn build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
